<?php
/**
 * @file
 * Ensures JavaScript callback handler has been setup properly.
 */

/**
 * Implements hook_requirements().
 */
function js_requirements($phase) {
  global $base_path;
  $requirements = array();
  $t = get_t();
  switch ($phase) {
    case 'runtime':
      $title = $t('JavaScript callback handler');
      // Warn about missing js.php in root directoy.
      if (!file_exists('js.php')) {
        $requirements['js'] = array(
          'title' => $title,
          'description' => $t('In order for JavaScript callbacks to work correctly, please <a hreg="!config_url">configure and download or auto-generate the js.php file</a>.', array(
            '!config_url' => $base_path . 'admin/config/system/js',
          )),
          'severity' => REQUIREMENT_ERROR,
          'value' => $t('Enable js.php'),
        );
      }
      // Warn about missing RewriteRule in .htaccess.
      elseif (strpos(file_get_contents('.htaccess'), 'js.php') === FALSE) {
        $requirements['js'] = array(
          'title' => $title,
          'description' => $t('To enable the JavaScript callback, please modify your .htaccess file. See <a href="!config_url">configuration page</a> and <a href="!readme_url">Readme.txt</a>', array(
            '!readme_url' => url(drupal_get_path('module', 'js') . '/README.txt'),
            '!config_url' => $base_path . 'admin/config/system/js',
          )),
          'severity' => REQUIREMENT_ERROR,
          'value' => $t('Add Apache RewriteRule'),
        );
      }
      // Return positive status message.
      else {
        $requirements['js'] = array(
          'title' => $title,
          'description' => t('The JavaScript callback handler has been installed correctly.'),
          'severity' => REQUIREMENT_OK,
          'value' => $t('Installed correctly'),
        );
      }
  }
  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function js_uninstall() {
  global $base_path;
  // Delete used variables.
  foreach (array(
    'js_callback_handler_complex_path',
    'js_callback_handler_page_arguments',
    'js_callback_handler_access_validation',
    'js_callback_handler_other_file',
    'js_autogenerate_hash'
  ) as $varname) {
    variable_del($varname);
  }
  // Delete auto-generated js.php from Drupal root.
  $hash_last = variable_get('js_autogenerate_hash', '');
  $filename = $_SERVER['DOCUMENT_ROOT'] . $base_path . 'js.php';
  if ($hash_last != '' && file_exists($file)) {
    $hash_current = md5(file_get_contents($file));
    if ($hash_current == $hash_last) {
      if (unlink($filename)) {
        drupal_set_message(t('Successfully removed js.php from your Drupal root directory.'));
      }
      else {
        drupal_set_message(t('Could not remove %filename from your Drupal root directory. Please remove it manually.', array(
          '%filename' => $filename,
        )));
      }
    }
  }
}
