<?php
/**
 * @file
 * JavaScript callback handler module.
 */

/**
 * Implements hook_menu().
 */
function js_menu() {
  $items = array();
  $items['admin/config/system/js'] = array(
    'title' => 'JS Callback handler',
    'description' => 'Configure JavaScript callback handler.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('js_configure_form'),
    'access arguments' => array('administer js'),
    'file' => 'js.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/system/js/download'] = array(
    'page callback' => 'js_download_handler',
    'access arguments' => array('administer js'),
    'file' => 'js.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/system/js/generate'] = array(
    'page callback' => 'js_generation_handler',
    'access arguments' => array('write to root'),
    'file' => 'js.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function js_permission() {
  return array(
    'administer js' => array(
      'title' => t('Administer JavaScript callback handler settings'),
    ),
    'write to root' => array(
      'title' => t('Allow saving the JS callback file directly to the Drupal root directory'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_disable().
 */
function js_disable() {
  // Remind of necessary .htaccess changes.
  drupal_set_message(t('Please remember to remove the changes in your .htaccess file!'), 'warning');
}
